### ISSUE TITLE
Hi~can't find the rfs/products/admin.py file

### ISSUE THREAD

**Issue by aaxaa** [dcrasch/react-flask-shop-app#1]
hi~can't find the rfs/products/admin.py file. so..it says:

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from rfs.app import create_app
  File "/home/vagrant/react-flask-shop-app/rfs/app.py", line 32, in <module>
    from rfs.products.admin import ProductAdmin
ImportError: No module named admin

**Comment by dcrasch** [comment]
added the rfs/products/admin.py, should work now.

go to: http://127.0.0.1:5000/products/ to manage the products
